"""Add preferences column to users table

Revision ID: ecefde06c0b7
Revises: 3d0baf7fbdf2
Create Date: 2025-09-20 19:24:56.051640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ecefde06c0b7'
down_revision: Union[str, Sequence[str], None] = '3d0baf7fbdf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
